[2024-01-16 16:10:30,477] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T16:10:29.097873+00:00 [queued]>
[2024-01-16 16:10:30,483] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T16:10:29.097873+00:00 [queued]>
[2024-01-16 16:10:30,483] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 16:10:30,483] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2024-01-16 16:10:30,484] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 16:10:30,492] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): check_file_if_exists> on 2024-01-16 16:10:29.097873+00:00
[2024-01-16 16:10:30,495] {standard_task_runner.py:52} INFO - Started process 1739 to run task
[2024-01-16 16:10:30,498] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_transfer_gdrive_to_postgresql', 'check_file_if_exists', 'manual__2024-01-16T16:10:29.097873+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/dag_gdrive_to_postgres.py', '--cfg-path', '/tmp/tmpzy7j1oj9', '--error-file', '/tmp/tmpnywuznar']
[2024-01-16 16:10:30,499] {standard_task_runner.py:80} INFO - Job 51: Subtask check_file_if_exists
[2024-01-16 16:10:30,532] {task_command.py:369} INFO - Running <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T16:10:29.097873+00:00 [running]> on host 3c1ede9470c0
[2024-01-16 16:10:30,580] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_transfer_gdrive_to_postgresql
AIRFLOW_CTX_TASK_ID=check_file_if_exists
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T16:10:29.097873+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-16T16:10:29.097873+00:00
[2024-01-16 16:10:33,645] {logging_mixin.py:115} INFO - Successfully install google-api-python-client
[2024-01-16 16:10:36,698] {logging_mixin.py:115} INFO - Successfully install google-auth-httplib2
[2024-01-16 16:10:39,812] {logging_mixin.py:115} INFO - Successfully install google-auth
[2024-01-16 16:10:42,924] {logging_mixin.py:115} INFO - Successfully install google-auth-oauthlib
[2024-01-16 16:10:42,937] {logging_mixin.py:115} INFO - Credentials from token ya29.a0AfB_byCbo1LuaVau_lph7bh7WjmnYEa740lh58RaXUYRjPfEc1xAYOFdmhd5-NtKhAcgpYTZSoZkkFC2aMHWHib8LJIFRlD5WJBZYON-TITr2Jb3lZI01KfKnV6F7e_-MGDSNZB-V9cpFMW_YKpo6ZhvimsHofRl5Fl7OgaCgYKAaQSARMSFQHGX2MiNQbSQHbzKQLVfmHflPJQAw0173
[2024-01-16 16:10:42,938] {logging_mixin.py:115} INFO - <google.oauth2.credentials.Credentials object at 0xffff9449d8d0>
[2024-01-16 16:10:44,046] {logging_mixin.py:115} INFO - [{'id': '1rzPInbJFi86HYocPCcptsDflfIYvkzqF', 'name': 'dataset'}]
[2024-01-16 16:10:44,047] {logging_mixin.py:115} INFO - The 'dataset' folder exists in 'Shared with me'.
[2024-01-16 16:10:44,424] {logging_mixin.py:115} INFO - dataset_files: [{'id': '1bORWzTe1VDOzGpiFpD0KJ78MN_rYr7gp', 'name': '2023-10-02.csv'}]
[2024-01-16 16:10:45,454] {logging_mixin.py:115} INFO - Downloaded file 2023-10-02.csv from Google Drive.
[2024-01-16 16:10:45,468] {python.py:173} INFO - Done. Returned value was: process_csv
[2024-01-16 16:10:45,484] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_transfer_gdrive_to_postgresql, task_id=check_file_if_exists, execution_date=20240116T161029, start_date=20240116T161030, end_date=20240116T161045
[2024-01-16 16:10:45,507] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-16 16:10:45,531] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
